---
title: "Data Dictionary"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**team_name**: The name of the team that the player played for during the time of the shot.

**game_date**: Date of the game in which the player shot the shot.

**season**: The season in which the player shot the shot.

**period**: an NBA game is divided in 4 periods of 12 mins each. For example, a value
for period = 1 refers to the first period (the first 12 mins of the game).

**minutes_remaining**: number of minutes before the current period of the game ends.

**seconds_remaining**: number of seconds before teh current period of the game ends.

**action_type**: type of shot the player attempted.

**shot_type**: whether the player attempted a 2 point field goal or 3 point field goal.

**shot_distance**: distance shot was attempted from the basket (measured in feet).

**opponent**: the team that the player was playing against.

**x_and_y**: court coordinates (measured in inches) where a shot occurred.

